version: "3.8"

networks:
  app_net:
    driver: bridge

volumes:
  postgres_db_volume:

secrets:
  psql_user: 
    file: ./secrets/psql_user.txt
  psql_pass:
    file: ./secrets/psql_pass.txt
  psql_db: 
    file: ./secrets/psql_db.txt

services:
  redis:
    image: redis:6.2.4
    container_name: redis
    networks:
      - app_net
    restart: always

  postgres_db:
    image: postgres:13.3
    container_name: postgres_db
    networks:
      - app_net
    restart: always
    volumes:
      - ./app/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - postgres_db_volume:/var/lib/postgresql/data
    secrets:
      - psql_user
      - psql_pass 
      - psql_db
    environment:
      POSTGRES_USER_FILE: /run/secrets/psql_user
      POSTGRES_PASSWORD_FILE: /run/secrets/psql_pass
      POSTGRES_DB_FILE: /run/secrets/psql_db

  app:
    build: .
    container_name: stress_table_app
    secrets:
      - psql_user
      - psql_pass 
      - psql_db
    environment:
      SERVER_ADDR: 0.0.0.0:8080
      REDIS_ADDR: redis:6379
      PG.HOST: postgres_db
      PG.PORT: 5432
      PG.POOL.MAX_SIZE: 16
    command: bash -c "cd ./app && cargo run --release"
    networks:
      - app_net
    ports:
      - 8080:8080
    depends_on:
      - redis
      - postgres_db
