[package]
name = "fe_model"
version = "0.2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
panic = 'abort'
codegen-units = 1
opt-level = 's'
lto = true

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { version = "0.2.74", features = ["serde-serialize"] }
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
js-sys = "0.3.51"


[dependencies.web-sys]
version = "0.3.51"
features = [
  'Document',
  'Window',
  'Element',
  'CustomEvent',
  'CustomEventInit',
  'EventTarget'
]
